apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28.4
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "echo the app is running! && sleep 3600"]
    - name: init-myservice
      image: busybox:1.28.4
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "until nslookup myservice; do echo waiting for myservice; sleep 2; done"]
    - name: init-mydb
      image: busybox:1.28.4
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "until nslookup mydb; do echo waiting for mydb; sleep 2; done"]
