apiVersion: v1
kind: Pod
metadata:
  name: affinity-required-pod
spec:
  containers:
    - name: myapp
      image: wangyanglinux/myapp:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - gke-node01
