apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-volume-cm
data:
  app.name: Hello Project
  app.version: 1.0.0
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: myapp
      image: wangyanglinux/myapp:v1
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "cat /etc/config/app.name"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: myapp-volume-cm
  restartPolicy: Never
