apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: myapp
      image: wangyanglinux/myapp:v1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: secret-volume
          mountPath: "/secret"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret
